global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - alerting-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: 'company-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['company-service:3002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']