route:
  receiver: default
  group_by: ['alertname', 'instance']
  routes:
    - matchers:
        - severity="critical"
      receiver: critical

receivers:
  - name: default
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: "#alerts"
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
    email_configs:
      - to: ${ALERT_EMAIL_TO}
        from: ${ALERT_EMAIL_FROM}
        smarthost: ${SMTP_HOST}:${SMTP_PORT}
        auth_username: ${SMTP_USER}
        auth_password: ${SMTP_PASS}

  - name: critical
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: "#alerts-critical"
        send_resolved: true
        title: "CRITICAL: {{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"